#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check Prettier standards
echo '🔍 Checking Prettier standards 🔍'
yarn format ||
(
    echo '❌ Prettier standards are not met ❌'
    false;
)
echo '✅ Prettier standards are met ✅'

# Run unit tests
echo '🧪 Running unit tests 🧪'
yarn workspace @elenaorfe/client test ||
(
    echo '❌ Unit tests failed ❌'
    false;
)
echo '✅ Unit tests successful ✅'

# Build the client
echo '🚧 Building the client 🚧'
yarn client:build ||
(
    echo '❌ Client build failed ❌'
    false;
)
echo '✅ Client build successful ✅'
