#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo '🚦 Pre-commit checks 🚦'

# Check vulnerabilities
echo '🐛 Checking vulnerabilities 🐛'
npm run audit ||
(
    echo '❌ Vulnerabilities found ❌'
    false;
)
echo '✅ No vulnerabilities found ✅'

# Check Prettier standards
echo '🔍 Checking Prettier standards 🔍'
npm run format ||
(
    echo '❌ Prettier standards are not met ❌'
    false;
)
echo '✅ Prettier standards are met ✅'

# Run unit tests
echo '🧪 Running unit tests 🧪'
npm run client:test ||
(
    echo '❌ Unit tests failed ❌'
    false;
)
echo '✅ Unit tests successful ✅'

# Build the client
echo '🚧 Building the client 🚧'
npm run client:build ||
(
    echo '❌ Client build failed ❌'
    false;
)
echo '✅ Client build successful ✅'
